#!/usr/bin/env ruby

require 'pry'
require 'RMagick'

def usage
  puts <<EOS
Usage: cup-magnitude filename
Usage: cat image | cup-magnitude
EOS
  exit 1
end

usage if ARGV.include? 'help'
usage if ARGV.include? '-h'
usage if ARGV.include? '--help'

file = ARGF.read

usage unless file



img = Magick::Image.from_blob(file).first
histogram = img.color_histogram

black = histogram[Magick::Pixel.from_color('black')]
black ||= 0;

puts black
